{% set name = "fastscape" %}
{% set version = "0.1.0beta" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fastscape-lem/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b08ba7ebd3693681db0832b193f21846e187b9bfdbe9a60f921a0f139e11c2c3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - xarray-simlab >=0.4.0
    - fastscapelib-f2py >=2.8.1
    - numba

test:
  imports:
    - fastscape

about:
  home: https://github.com/fastscape-lem/fastscape
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Fast, versatile and user-friendly landscape evolution models'
  doc_url: https://fastscape.readthedocs.io
  dev_url: https://github.com/fastscape-lem/fastscape

extra:
  recipe-maintainers:
    - benbovy
